### ISSUE TITLE
Swift symbols demangling

### ISSUE THREAD

**Issue by MaxDesiatov** [kateinoigakukun/wasminspect#10]
I know this is a very language-specific features, but I hope there's a chance to implement this, would make it much easier to read Swift backtraces.

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Could you try this feature? https://github.com/kateinoigakukun/wasminspect#swift-extension

**Comment by MaxDesiatov** [comment]
This is fantastic, thank you very much! Probably the only issue was that the feature required rust nightly and had to be built with `cargo +nightly build --features swift-extension` or maybe I'm missing something?

**Comment by kateinoigakukun** [comment]
Ah, yes, maybe I used some unstable features 😅

**Comment by MaxDesiatov** [comment]
Cool, no problem, I think this can be closed now. 👍
