### ISSUE TITLE
Support recent wasmtime scheme

### ISSUE THREAD

**Issue by ggreif** [kateinoigakukun/wasminspect#21]
Recent changes to `wasmtime` include the invocation of `_start`.
The `(start $<entry>)` directive in the `.wasm` file is only invoked once, to run the constructors (for initialising the heap and vars).

So when there is a `_start` I'd suggest that `run` gets following meaning:
- invoke `(start $<entry>)`, if not done yet, remember it
- invoke `_start`.

**Comment by ggreif** [comment]
Currently I have the choice:
- `run` -> only runs `(start $<entry>)`
- `run _start` -> won't run `(start $<entry>)`, but `_start` and the necessary globals are not set up.

**Comment by kateinoigakukun** [comment]
Sorry for my late response. I applied this startup scheme. Please check it in master branch 🙏

**Comment by ggreif** [comment]
Yes, this works now. Thanks for the fix!
